triggers:
- description: null
  envs: []
  last_enabled_at: 2024-10-08 23:36:17.124767
  name: hourly_health_check
  pipeline_uuid: health_checks
  schedule_interval: '30 * * * * '
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-10-06 01:22:00
  status: inactive
  token: 5d0431e1d4da484b99510ea94b1a83b1
  variables: {}
