triggers:
- description: null
  envs: []
  last_enabled_at: 2024-10-16 18:06:47.165954
  name: monthly calibration
  pipeline_uuid: calibration_factors
  schedule_interval: '@monthly'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-11-01 00:00:00
  status: inactive
  token: 58e8e979ba6a4adab2a1e9bcd134e1cc
  variables: {}
