triggers:
- description: null
  envs: []
  last_enabled_at: 2024-12-04 11:59:02.444182
  name: hourly fiuna data
  pipeline_uuid: etl_fiuna_bronze
  schedule_interval: '@hourly'
  schedule_type: time
  settings:
    timeout: '120'
  sla: null
  start_time: 2024-10-02 03:17:00
  status: inactive
  token: 2a8157b8ee7a4b5ab22ccbafcb06fe27
  variables: {}
