triggers:
- description: null
  envs: []
  last_enabled_at: 2024-10-02 03:15:58.196779
  name: hourly meteostat updates
  pipeline_uuid: etl_meteostat_bronze
  schedule_interval: '@hourly'
  schedule_type: time
  settings: null
  sla: null
  start_time: 2024-10-02 03:15:00
  status: active
  token: a2a39737348b4c79a6ac577c2c4802de
  variables:
    execution_type: incremental
